### ISSUE TITLE
공공데이터에서 제공하는 휴게소 데이터 중 `누락된/이름이 변경된 휴게소`를 업데이트

### ISSUE THREAD

**Issue by jun108059** [Nexters/8potatoes-server#32]
## ✍🏻 Description

공공데이터에서 제공하는 휴게소 데이터 중에 최신화되지 않은 데이터를 업데이트해야합니다.

## ✅ To-Do

- [ ] 기존 공공데이터 API <-> 하이쉼 API 데이터 비교
- [ ] 추가/업데이트 시 다른 API에서 참조하는 데이터 모두 구성 가능한지 검토
- [ ] 예시) 메뉴, 주유소, 편의시설 등
