### ISSUE TITLE
Object storage에 이미지 업로드 및 URL 조회 기능

### ISSUE THREAD

**Issue by jun108059** [Nexters/8potatoes-server#33]
## ✍🏻 Description

`편의시설 이미지`와 `브랜드 이미지`, `휴게소 대표 메뉴 이미지` 3종류를 NCP에 업로드에서 서버에서 URL을 조회하고 API 응답에 추가합니다.

## ✅ To-Do

- [x] 1) NCP Object Storage 설정
- [x] 2) 서버에서 이미지 업로드 기능 구현
- [x] 3) URL을 API response에 추가

### 1) NCP Object Storage 생성

- [NCP Object Storage API](https://api.ncloud-docs.com/docs/common-objectstorageapi-objectstorageapi#1%EC%9D%B8%EC%A6%9D%ED%82%A4%EC%83%9D%EC%84%B1)

- 버킷 name : `8potatoes`
- 폴더구조 : `TBD`

### 2) API 인증 정보 생성

- [NCP Ncloud API](https://api.ncloud-docs.com/docs/common-ncpapi#1-%EC%9D%B8%EC%A6%9D%ED%82%A4-%EC%83%9D%EC%84%B1)
- Access Key & Secret Key 발급
