### ISSUE TITLE
Flyway 적용

### ISSUE THREAD

**Issue by jun108059** [Nexters/8potatoes-server#38]
## ✍🏻 Description

Flyway를 적용하여 데이터베이스 마이그레이션 관리 기능을 추가하는 Task입니다.

## ✅ To-Do

- [ ] Flyway 의존성 추가 (`build.gradle.kts` 수정)
- [ ] 초기 마이그레이션 파일 작성 (현재 DB 스키마 반영)
- [ ] 애플리케이션 실행 시 Flyway 마이그레이션 자동 적용 테스트

## 📨 ETC

- Flyway는 기본적으로 `/db/migration` 경로에 있는 SQL 파일을 읽어들여 마이그레이션을 수행
- 이 경로를 변경하거나 다른 옵션이 필요하면 `application.yml`에서 설정 가능
